title: Expose Fake Clinics PGH
author: Pittsburgh DSA Socialist Feminist Committee
description: |
  A project by the Pittsburgh DSA Socialist Feminist Committee
email: socfem@pghdsa.org

baseurl: ''
url: 'http://www.exposefakeclinicspgh.com'

theme_settings:
  favicon: assets/favicon.png
  avatar: assets/img/rose-40.png

  rss: false
  facebook: # TODO: check to see if there is a Facebook page for this campaign, if not, add PGHDSA's facebook page
  twitter: 'pghdsa'

  google_analytics: 'UA-113368884-1'
  portfolio: false
  search: false
  tags: false

  str_follow_on: 'Follow on'
  str_rss_follow: 'Follow RSS feed'
  str_email: 'Email'
  str_next_post: 'Next post'
  str_previous_post: 'Previous post'
  str_next_page: 'Next'
  str_previous_page: 'Prev'
  str_continue_reading: 'Continue reading'
  str_javascript_required_disqus: 'Please enable JavaScript to view comments.'

  google_fonts: 'Lato:400,400i,700,700i'

  post_navigation: true

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- vendor
